model: resnet50
preprocessing: standardization
augmentation: cutmix
precision: float32
batch_size: 128
partitioning: 80-10-10
lr: 0.01
lr_schedule: exponential
optimizer_momentum: 0.99
optimizer: SGD
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.258
