model: resnet50
preprocessing: minmax
augmentation: random
precision: global_policy_float16
batch_size: 1
partitioning: 60-20-20
lr: 0.00015
lr_schedule: cosine
optimizer_momentum: 0.5
optimizer: AdamW
weight_decay: 0.01
quantization: pre
internal_optimizations: jit_compilation
