model: resnet50
preprocessing: None
augmentation: mixup
precision: float32
batch_size: 32
partitioning: 60-20-20
lr: 0.00625
lr_schedule: constant
optimizer_momentum: 0.5
optimizer: RMSProp
weight_decay: 1e-05
quantization: pre
internal_optimizations: jit_compilation
