model: resnet50
preprocessing: None
augmentation: random
precision: global_policy_float16
batch_size: 32
partitioning: 70-15-15
lr: 0.01
lr_schedule: exponential
optimizer_momentum: 0.0
optimizer: AdamW
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.009
