model: resnet50
preprocessing: robust_scaling
augmentation: random
precision: float64
batch_size: 32
partitioning: 80-10-10
lr: 0.00015
lr_schedule: constant
optimizer_momentum: 0.99
optimizer: Adam
internal: post_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.01
