model: resnet50
preprocessing: standardization
augmentation: cutmix
precision: float64
batch_size: 64
partitioning: 80-10-10
lr: 0.01
lr_schedule: cosine
optimizer_momentum: 0.9
optimizer: RMSProp
internal: post_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.009
