# Step 1: configure sweep
sweep_configuration = {
  'method': 'random', # other options: grid, bayes
  'name': 'sweep',
  'metric': {'goal': 'minimize',
             'name': 'loss' # if we choose other metrics, we have to log the variable in our python script
             },
  'parameters':
      {
        'batch_size': {'values': [16, 32, 64]},
        'epochs': {'values': [5, 10, 15]},
        'lr': {'values': [1.5e-4, 2.0e-4, 8.0e-4, 6.25e-3]}, # explain in paper why we used convnext training methods
        # 'lr_schedule': {'values': ['cosine_decay', 'step_decay', 'constant', 'time_based']},
        'optimizer': {'values': ['SGD', 'Adam', AdamW', 'RMSProp']},
        'optimizer_momentum' {'values': [[0.9, 0.95], [0.9, 0.999]]} # main file has to accept list
     }
}

# TO BE COPIED INTO PYTHON FILE :::

# Step 2: initialize sweep
# import wandp
# sweep_id = wandb.sweep(sweep=sweep_configuration, project="pomodoro")

# Step 3: start sweep agents
# wandb.agent(sweep_id=sweep_id, function=function_name) # sweep_id is returned after sweep is initialized

# https://docs.wandb.ai/guides/sweeps/add-w-and-b-to-your-code