model: resnet50
preprocessing: None
augmentation: random
precision: float32
batch_size: 4
partitioning: 80-10-10
lr: 0.01
lr_schedule: constant
optimizer_momentum: 0.99
optimizer: AdamW
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.012
