model: resnet50
preprocessing: standardization
augmentation: cutmix
precision: float16
batch_size: 32
partitioning: 90-5-5
lr: 0.0008
lr_schedule: exponential
optimizer_momentum: 0.9
optimizer: Adam
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.379
