model: resnet50
preprocessing: None
augmentation: None
precision: float32
batch_size: 64
partitioning: 70-15-15
lr: 0.00625
lr_schedule: polynomial
optimizer_momentum: 0.99
optimizer: AdamW
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.028
