model: resnet50
preprocessing: standardization
augmentation: cutmix
precision: global_policy_float16
batch_size: 64
partitioning: 70-15-15
lr: 0.0008
lr_schedule: constant
optimizer_momentum: 0.99
optimizer: Adam
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.447
