model: resnet50
preprocessing: robust_scaling
augmentation: mixup
precision: float32
batch_size: 128
partitioning: 60-20-20
lr: 0.00015
lr_schedule: constant
optimizer_momentum: 0.99
optimizer: Adam
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.818
