model: resnet50
preprocessing: robust_scaling
augmentation: None
precision: global_policy_float16
batch_size: 128
partitioning: 80-10-10
lr: 0.00015
lr_schedule: constant
optimizer_momentum: 0.5
optimizer: RMSProp
internal: pre_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.947
