model: resnet50
preprocessing: minmax
augmentation: None
precision: float64
batch_size: 4
partitioning: 70-15-15
lr: 0.00015
lr_schedule: polynomial
optimizer_momentum: 0.5
optimizer: Adam
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.174
