model: resnet50
preprocessing: standardization
augmentation: None
precision: float32
batch_size: 64
partitioning: 80-10-10
lr: 0.00015
lr_schedule: constant
optimizer_momentum: 0.0
optimizer: Adam
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.904
