model: resnet50
preprocessing: robust_scaling
augmentation: random
precision: global_policy_float16
batch_size: 4
partitioning: 80-10-10
lr: 0.00625
lr_schedule: exponential
optimizer_momentum: 0.0
optimizer: AdamW
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.01
