model: resnet50
preprocessing: minmax
augmentation: None
precision: global_policy_float16
batch_size: 64
partitioning: 80-10-10
lr: 0.00625
lr_schedule: polynomial
optimizer_momentum: 0.0
optimizer: Adam
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.682
