model: resnet50
preprocessing: None
augmentation: cutmix
precision: float64
batch_size: 64
partitioning: 90-5-5
lr: 0.00015
lr_schedule: exponential
optimizer_momentum: 0.9
optimizer: AdamW
internal: post_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.008
