model: resnet50
preprocessing: robust_scaling
augmentation: random
precision: float64
batch_size: 128
partitioning: 70-15-15
lr: 0.0008
lr_schedule: cosine
optimizer_momentum: 0.5
optimizer: SGD
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.082
