model: resnet50
preprocessing: minmax
augmentation: None
precision: global_policy_float16
batch_size: 4
partitioning: 60-20-20
lr: 0.00015
lr_schedule: constant
optimizer_momentum: 0.5
optimizer: SGD
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.134
