model: resnet50
preprocessing: None
augmentation: random
precision: float64
batch_size: 64
partitioning: 70-15-15
lr: 0.00625
lr_schedule: cosine
optimizer_momentum: 0.9
optimizer: RMSProp
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.052
