model: resnet50
preprocessing: standardization
augmentation: cutmix
precision: float64
batch_size: 64
partitioning: 60-20-20
lr: 0.0008
lr_schedule: constant
optimizer_momentum: 0.5
optimizer: SGD
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.213
