model: resnet50
preprocessing: robust_scaling
augmentation: cutmix
precision: global_policy_float16
batch_size: 32
partitioning: 80-10-10
lr: 0.01
lr_schedule: constant
optimizer_momentum: 0.9
optimizer: Adam
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.244
