model: resnet50
preprocessing: minmax
augmentation: mixup
precision: float16
batch_size: 4
partitioning: 90-5-5
lr: 0.0008
lr_schedule: constant
optimizer_momentum: 0.0
optimizer: Adam
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.115
