model: resnet50
preprocessing: robust_scaling
augmentation: cutmix
precision: float32
batch_size: 128
partitioning: 70-15-15
lr: 0.00625
lr_schedule: polynomial
optimizer_momentum: 0.0
optimizer: AdamW
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.018
