model: resnet50
preprocessing: robust_scaling
augmentation: cutmix
precision: float64
batch_size: 128
partitioning: 70-15-15
lr: 0.00015
lr_schedule: polynomial
optimizer_momentum: 0.99
optimizer: SGD
internal: pre_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.141
