model: resnet50
preprocessing: standardization
augmentation: None
precision: float64
batch_size: 128
partitioning: 80-10-10
lr: 0.0008
lr_schedule: polynomial
optimizer_momentum: 0.99
optimizer: SGD
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.67
