model: resnet50
preprocessing: None
augmentation: None
precision: float32
batch_size: 32
partitioning: 60-20-20
lr: 0.00015
lr_schedule: exponential
optimizer_momentum: 0.0
optimizer: AdamW
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.01
