model: resnet50
preprocessing: robust_scaling
augmentation: random
precision: float64
batch_size: 32
partitioning: 60-20-20
lr: 0.00625
lr_schedule: cosine
optimizer_momentum: 0.0
optimizer: Adam
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.036
