model: resnet50
preprocessing: standardization
augmentation: mixup
precision: global_policy_float16
batch_size: 32
partitioning: 60-20-20
lr: 0.00625
lr_schedule: exponential
optimizer_momentum: 0.0
optimizer: RMSProp
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.484
