model: resnet50
preprocessing: None
augmentation: cutmix
precision: float16
batch_size: 64
partitioning: 90-5-5
lr: 0.00015
lr_schedule: exponential
optimizer_momentum: 0.9
optimizer: Adam
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.584
