model: resnet50
preprocessing: standardization
augmentation: mixup
precision: float16
batch_size: 64
partitioning: 90-5-5
lr: 0.00625
lr_schedule: constant
optimizer_momentum: 0.0
optimizer: RMSProp
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.007
