model: resnet50
preprocessing: standardization
augmentation: mixup
precision: global_policy_float16
batch_size: 4
partitioning: 60-20-20
lr: 0.00625
lr_schedule: constant
optimizer_momentum: 0.5
optimizer: SGD
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.102
