model: resnet50
preprocessing: standardization
augmentation: random
precision: float64
batch_size: 64
partitioning: 60-20-20
lr: 0.01
lr_schedule: polynomial
optimizer_momentum: 0.99
optimizer: Adam
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.554
