model: resnet50
preprocessing: None
augmentation: cutmix
precision: float32
batch_size: 64
partitioning: 60-20-20
lr: 0.0008
lr_schedule: exponential
optimizer_momentum: 0.0
optimizer: SGD
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.151
