model: resnet50
preprocessing: minmax
augmentation: mixup
precision: global_policy_float16
batch_size: 32
partitioning: 80-10-10
lr: 0.0008
lr_schedule: cosine
optimizer_momentum: 0.5
optimizer: Adam
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.128
