model: resnet50
preprocessing: robust_scaling
augmentation: None
precision: float64
batch_size: 128
partitioning: 60-20-20
lr: 0.01
lr_schedule: cosine
optimizer_momentum: 0.5
optimizer: Adam
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.098
