model: resnet50
preprocessing: None
augmentation: mixup
precision: global_policy_float16
batch_size: 4
partitioning: 80-10-10
lr: 0.0008
lr_schedule: exponential
optimizer_momentum: 0.5
optimizer: RMSProp
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.035
