model: resnet50
preprocessing: minmax
augmentation: random
precision: float16
batch_size: 64
partitioning: 90-5-5
lr: 0.01
lr_schedule: polynomial
optimizer_momentum: 0.99
optimizer: SGD
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.059
