model: resnet50
preprocessing: None
augmentation: None
precision: float16
batch_size: 1
partitioning: 60-20-20
lr: 0.01
lr_schedule: constant
optimizer_momentum: 0.0
optimizer: RMSProp
weight_decay: 0.01
quantization: None
internal_optimizations: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.012