model: resnet50
preprocessing: standardization
augmentation: mixup
precision: float32
batch_size: 4
partitioning: 70-15-15
lr: 0.0008
lr_schedule: exponential
optimizer_momentum: 0.9
optimizer: AdamW
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.009
