model: resnet50
preprocessing: standardization
augmentation: mixup
precision: float16
batch_size: 32
partitioning: 80-10-10
lr: 0.01
lr_schedule: exponential
optimizer_momentum: 0.9
optimizer: Adam
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.45
