model: resnet50
preprocessing: None
augmentation: cutmix
precision: float32
batch_size: 128
partitioning: 70-15-15
lr: 0.00015
lr_schedule: exponential
optimizer_momentum: 0.0
optimizer: Adam
internal: post_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.011
