model: resnet50
preprocessing: None
augmentation: random
precision: float64
batch_size: 64
partitioning: 60-20-20
lr: 0.0008
lr_schedule: constant
optimizer_momentum: 0.5
optimizer: AdamW
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.021
