model: resnet50
preprocessing: None
augmentation: None
precision: float64
batch_size: 32
partitioning: 60-20-20
lr: 0.00015
lr_schedule: cosine
optimizer_momentum: 0.99
optimizer: AdamW
internal: post_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.011
