model: resnet50
preprocessing: robust_scaling
augmentation: random
precision: global_policy_float16
batch_size: 32
partitioning: 60-20-20
lr: 0.00015
lr_schedule: constant
optimizer_momentum: 0.9
optimizer: Adam
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.863
