model: resnet50
preprocessing: None
augmentation: mixup
precision: float16
batch_size: 64
partitioning: 90-5-5
lr: 0.00625
lr_schedule: cosine
optimizer_momentum: 0.5
optimizer: SGD
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.121
