model: resnet50
preprocessing: robust_scaling
augmentation: cutmix
precision: float32
batch_size: 4
partitioning: 60-20-20
lr: 0.00625
lr_schedule: cosine
optimizer_momentum: 0.9
optimizer: Adam
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.01
