configuration:
  preprocessing:
    values:
    - None
    - standardization
    - robust_scaling
    - minmax
  augmentation:
    values:
    - None
    - random
    - mixup
    - cutmix
  precision:
    values:
    - float16
    - float32 
    - float64
    - global_policy_float16
  batch_size:
    values:
    - 1
    - 32
    - 64
    - 128
  partitioning:
    values:
    - 60-20-20
    - 70-15-15
    - 80-10-10
    - 90-5-5
  lr: # convnext2 appendix
    values:
    - 0.01 # baseline SGD
    - 1.5e-4
    - 8.0e-4
    - 6.25e-3
  lr_schedule:
    values:
    - constant
    - exponential
    - polynomial
    - cosine
  optimizer_momentum:
    values:
    - 0.0
    - 0.5
    - 0.9
    - 0.99
  optimizer:
    values:
    - RMSProp
    - SGD
    - Adam
    - AdamW
  internal:
    values:
    - None
    - pre_quantization
    - post_quantization
    - jit_compilation