model: resnet50
preprocessing: minmax
augmentation: random
precision: float32
batch_size: 128
partitioning: 70-15-15
lr: 0.00015
lr_schedule: constant
optimizer_momentum: 0.9
optimizer: Adam
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.825
