model: resnet50
preprocessing: None
augmentation: None
precision: float64
batch_size: 32
partitioning: 80-10-10
lr: 0.00015
lr_schedule: polynomial
optimizer_momentum: 0.0
optimizer: AdamW
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.01
