model: resnet50
preprocessing: None
augmentation: random
precision: float16
batch_size: 64
partitioning: 80-10-10
lr: 0.00015
lr_schedule: polynomial
optimizer_momentum: 0.9
optimizer: AdamW
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.022
