model: resnet50
preprocessing: robust_scaling
augmentation: random
precision: float32
batch_size: 32
partitioning: 60-20-20
lr: 0.00625
lr_schedule: cosine
optimizer_momentum: 0.5
optimizer: SGD
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.127
