model: resnet50
preprocessing: minmax
augmentation: mixup
precision: global_policy_float16
batch_size: 16
partitioning: 90-5-5
lr: 0.00015
lr_schedule: constant
optimizer_momentum: 0.99
optimizer: RMSProp
weight_decay: 1e-05
quantization: None
internal_optimizations: weight_pruning
