model: resnet50
preprocessing: None
augmentation: random
precision: float16
batch_size: 64
partitioning: 80-10-10
lr: 0.00015
lr_schedule: exponential
optimizer_momentum: 0.5
optimizer: Adam
weight_decay: 0.001
quantization: None
internal_optimizations: weight_clustering
