model: resnet50
preprocessing: None
augmentation: cutmix
precision: global_policy_float16
batch_size: 64
partitioning: 90-5-5
lr: 0.01
lr_schedule: exponential
optimizer_momentum: 0.5
optimizer: Adam
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.354
