model: resnet50
preprocessing: None
augmentation: cutmix
precision: float64
batch_size: 128
partitioning: 80-10-10
lr: 0.00625
lr_schedule: cosine
optimizer_momentum: 0.9
optimizer: Adam
internal: pre_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.009
