model: resnet50
preprocessing: minmax
augmentation: None
precision: global_policy_float16
batch_size: 32
partitioning: 90-5-5
lr: 0.0008
lr_schedule: constant
optimizer_momentum: 0.9
optimizer: AdamW
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.009
