model: resnet50
preprocessing: None
augmentation: mixup
precision: global_policy_float16
batch_size: 64
partitioning: 70-15-15
lr: 0.00015
lr_schedule: polynomial
optimizer_momentum: 0.99
optimizer: SGD
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.753
