model: resnet50
preprocessing: minmax
augmentation: random
precision: global_policy_float16
batch_size: 4
partitioning: 70-15-15
lr: 0.00625
lr_schedule: polynomial
optimizer_momentum: 0.99
optimizer: SGD
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.01
