model: resnet50
preprocessing: standardization
augmentation: None
precision: float16
batch_size: 64
partitioning: 80-10-10
lr: 0.0008
lr_schedule: exponential
optimizer_momentum: 0.5
optimizer: RMSProp
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.963
