model: resnet50
preprocessing: standardization
augmentation: mixup
precision: float64
batch_size: 64
partitioning: 60-20-20
lr: 0.01
lr_schedule: cosine
optimizer_momentum: 0.99
optimizer: Adam
internal: post_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.009
