model: resnet50
preprocessing: None
augmentation: cutmix
precision: float32
batch_size: 128
partitioning: 70-15-15
lr: 0.01
lr_schedule: constant
optimizer_momentum: 0.99
optimizer: AdamW
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.08
