model: resnet50
preprocessing: None
augmentation: None
precision: float64
batch_size: 4
partitioning: 80-10-10
lr: 0.00625
lr_schedule: polynomial
optimizer_momentum: 0.0
optimizer: Adam
internal: post_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.01
