model: resnet50
preprocessing: None
augmentation: cutmix
precision: float16
batch_size: 4
partitioning: 70-15-15
lr: 0.0008
lr_schedule: constant
optimizer_momentum: 0.5
optimizer: RMSProp
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.023
