model: resnet50
preprocessing: minmax
augmentation: random
precision: float64
batch_size: 32
partitioning: 60-20-20
lr: 0.00625
lr_schedule: exponential
optimizer_momentum: 0.99
optimizer: AdamW
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.013
