model: resnet50
preprocessing: robust_scaling
augmentation: mixup
precision: global_policy_float16
batch_size: 128
partitioning: 60-20-20
lr: 0.01
lr_schedule: exponential
optimizer_momentum: 0.9
optimizer: AdamW
weight_decay: 0.0001
quantization: post_weights_and_activations
internal_optimizations: weight_clustering
seed : 22
n_parameters: 23792612