model: resnet50
preprocessing: minmax
augmentation: mixup
precision: global_policy_float16
batch_size: 32
partitioning: 70-15-15
lr: 0.00015
lr_schedule: polynomial
optimizer_momentum: 0.99
optimizer: AdamW
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.009
