model: resnet50
preprocessing: robust_scaling
augmentation: mixup
precision: global_policy_float16
batch_size: 32
partitioning: 90-5-5
lr: 0.0008
lr_schedule: cosine
optimizer_momentum: 0.99
optimizer: SGD
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.019
