model: resnet50
preprocessing: minmax
augmentation: random
precision: global_policy_float16
batch_size: 64
partitioning: 90-5-5
lr: 0.00015
lr_schedule: constant
optimizer_momentum: 0.0
optimizer: Adam
weight_decay: 0.01
quantization: post_weights_and_activations
internal_optimizations: None
