model: resnet50
preprocessing: minmax
augmentation: mixup
precision: global_policy_float16
batch_size: 64
partitioning: 60-20-20
lr: 0.0008
lr_schedule: cosine
optimizer_momentum: 0.9
optimizer: SGD
internal: post_quantization
seed : 22
n_parameters: 23792612
test_accuracy: 0.108
