model: resnet50
preprocessing: standardization
augmentation: mixup
precision: global_policy_float16
batch_size: 64
partitioning: 90-5-5
lr: 0.00625
lr_schedule: polynomial
optimizer_momentum: 0.5
optimizer: SGD
weight_decay: 0.001
quantization: post_weights_and_activations
internal_optimizations: weight_clustering
