model: resnet50
preprocessing: standardization
augmentation: cutmix
precision: float64
batch_size: 4
partitioning: 90-5-5
lr: 0.0008
lr_schedule: exponential
optimizer_momentum: 0.9
optimizer: SGD
internal: post_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.009
