model: resnet50
preprocessing: minmax
augmentation: random
precision: float64
batch_size: 128
partitioning: 90-5-5
lr: 0.0008
lr_schedule: constant
optimizer_momentum: 0.0
optimizer: AdamW
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.06
