model: resnet50
preprocessing: standardization
augmentation: cutmix
precision: float16
batch_size: 64
partitioning: 80-10-10
lr: 0.01
lr_schedule: exponential
optimizer_momentum: 0.5
optimizer: Adam
internal: None
seed : 22
n_parameters: 23792612
test_accuracy: 0.332
