model: resnet50
preprocessing: robust_scaling
augmentation: random
precision: global_policy_float16
batch_size: 4
partitioning: 90-5-5
lr: 0.00015
lr_schedule: polynomial
optimizer_momentum: 0.9
optimizer: AdamW
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.01
