model: resnet50
preprocessing: minmax
augmentation: None
precision: float64
batch_size: 128
partitioning: 90-5-5
lr: 0.0008
lr_schedule: constant
optimizer_momentum: 0.5
optimizer: SGD
internal: jit_compilation
seed : 22
n_parameters: 23792612
test_accuracy: 0.798
