model: resnet50
preprocessing: None
augmentation: None
precision: float32
batch_size: 64
partitioning: 60-20-20
lr: 0.00625
lr_schedule: constant
optimizer_momentum: 0.9
optimizer: SGD
internal: post_quantization
seed : 22
n_parameters: 23846055
test_accuracy: 0.01
